### ISSUE TITLE
setSelection for out range 

### ISSUE THREAD

**Issue by orwant** [google/google-visualization-issues#1289]
```
TO OPEN A BUG/FEATURE REQUEST PLEASE FOLLOW THE INSTRUCTIONS BELOW,
OTHERWISE IT MAY BE IGNORED.

1. Use a global variable:
 Chart = new google.visualization.PieChart(document.getElementById('piechart'))
 to draw Pie chart with data :[
          ['Task', 'Hours per Day'],
          ['Work',     2000],
          ['Eat',      5000],
          ['Commute',  6000],
          ['Watch TV', 7000],
          ['Sleep',    7]
        ] 

2. After chart created, use method setSelected():
   Chart.setSelection([{row:4}]
   Appear error "TypeError: b[Jb] is undefined". Because 'Sleep' value too small so
it have not present on chart. And after setSelected() method can not use for every
other exist index.

Thanks!

```

Original issue reported on code.google.com by `meoghe1582` on 2013-08-20 10:51:58

<hr>
- _Attachment: [pie chart.htm](https://storage.googleapis.com/google-code-attachments/google-visualization-api-issues/issue-1289/comment-0/pie chart.htm)_

**Comment by orwant** [comment]
```
I believe this will be fixed in the next release, which may come out today.
```

Original issue reported on code.google.com by `dlaliberte@google.com` on 2013-08-21 12:49:16

**Comment by orwant** [comment]
```
Does the Chart.setSelection() work on PieCharts when using Java GWT?
We have the following:

final JsArray<Selection> selectionArray = Selection.createArray().cast();
selectionArray.setLength(1);

final Selection selection = Selection.create(1, null).cast();
selectionArray.set(0, selection);


but we keep getting the error:

com.google.gwt.core.client.JavaScriptException: (TypeError) @com.googlecode.gwt.charts.client.ChartObject::setSelection(Lcom/google/gwt/core/client/JsArray;)([JavaScript
object(10448)]): Cannot read property 'NaN' of undefined
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:249)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:571)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeVoid(ModuleSpace.java:299)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeVoid(JavaScriptHost.java:107)
    at com.googlecode.gwt.charts.client.ChartObject$.setSelection$(ChartObject.java)
    at com.googlecode.gwt.charts.client.corechart.CoreChartWidget.setSelection(CoreChartWidget.java:90)

```

Original issue reported on code.google.com by `atmbestportal` on 2014-01-06 14:09:05

**Comment by orwant** [comment]
```
@atmbestportal The java stack trace suggests this might be a bug in GWT Charts, which
is a third-party compatibility layer to wrap Gviz in GWT. It is not the package that
we support.  You might try posting in their issue tracker: https://code.google.com/p/gwt-charts/issues/list
```

Original issue reported on code.google.com by `dlaliberte@google.com` on 2014-01-07 15:09:51

**Comment by orwant** [comment]
```
Thank you dlalibe.
I have posted a question on the link you provided.
```

Original issue reported on code.google.com by `atmbestportal` on 2014-01-07 18:36:21
