### ISSUE TITLE
GWT-visualization library suddenly returns error when drawing chart

### ISSUE THREAD

**Issue by hansoncry** [google/google-visualization-issues#2714]
Since one hour ago, our application has begun to get the following error when loading Pie chart powered by Google visualization library. I suspect it's caused the visualization JS code has been corrupted since there is no recent code change from our side and the error suddenly began to show up. The application is built using GWT 2.8.2 and gwt-visualization 1.1.2

`
com.google.gwt.core.client.JavaScriptException: (TypeError) @com.google.gwt.visualization.client.DataTable::create()([]): $wnd.google is undefined
	at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:252)
	at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:121)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:573)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:293)
	at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
	at com.google.gwt.visualization.client.DataTable$.create(DataTable.java) 
`

**Comment by mattpoole** [comment]
possibly related to jsapi being unavailable since at least 4pm ET (502 error)

https://www.google.com/jsapi

**Comment by hansoncry** [comment]
That makes sense. Thank you @mattpoole .

**Comment by edspivak** [comment]
Are there any ETA on a resolution? Is there anyone at google looking into it?

**Comment by mattpoole** [comment]
Not that I have seen, But also just found this posted 10 minutes ago by google dude

https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code

> Also, in preparation for this turndown of the old server, there will be short periods of outages, maybe up to a few hours, during which the UDS server is "drained" of all requests to determine if there are any further unknowns.  You may have noticed one already.   You can avoid these outages by updating to the new loader, as linked to above.

**Comment by edspivak** [comment]
Thank you @mattpoole .

**Comment by mattpoole** [comment]
"short" == "a few hours" apparently

**Comment by denaliwhite** [comment]
jsapi is back up. 
https://www.google.com/jsapi

Our related issues resolved when it was restored.
